/** TajStay transactional email brand tokens (inline-safe for email clients). */
export const EMAIL_BRAND = {
  greenDeep: "#071a10",
  greenDark: "#0a3d2e",
  greenPrimary: "#14532d",
  greenButton: "#166534",
  greenAccent: "#16a34a",
  greenSoft: "#dcfce7",
  gold: "#d4a843",
  goldDark: "#a07c2e",
  goldLine: "#e8c468",
  white: "#ffffff",
  cream: "#fffef7",
  ink: "#0f172a",
  inkMuted: "#475569",
  inkSoft: "#64748b",
  border: "#e2e8f0",
  success: "#15803d",
  successBg: "#f0fdf4",
  warning: "#b45309",
  warningBg: "#fffbeb",
  danger: "#b91c1c",
  dangerBg: "#fef2f2",
  info: "#0a3d2e",
  infoBg: "#ecfdf5",
  fontUi:
    "'DM Sans', Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  fontDisplay: "'Playfair Display', Georgia, 'Times New Roman', Times, serif",
  fontMono: "'SF Mono', 'Roboto Mono', Menlo, Consolas, monospace",
  maxWidth: 600
} as const;
